### ISSUE TITLE
stackplot needs more adjustable settings

### ISSUE THREAD

**Issue by stestoll** [StollLab/EasySpin#105]
**[Original report](https://bitbucket.org/sstoll/easyspin/issue/105) by Stefan Stoll (Bitbucket: [557058:d9c9844b-aee7-4711-bae2-ecebcf6694cf](https://bitbucket.org/557058:d9c9844b-aee7-4711-bae2-ecebcf6694cf), GitHub: [sstoll](https://github.com/sstoll)).**

----------------------------------------

```stackplot``` is very limited. It needs a complete redesign, including user control over scaling, stacking, and labeling.

See associated forum post [here](http://easyspin.org/forum/viewtopic.php?f=4&t=489).

Here is an example that shows a case where the labels on the vertical axis are not positioned adequately:

```
#!matlab
clear, clf, clc

Sys.g = 2;
Sys.lw = 1;
Exp.mwFreq = 9.5;
[x,y] = pepper(Sys,Exp);
y = [y;y;y];

stackplot(x,y);

```

**Comment by cetait** [comment]
Issue addressed in commit [eb43544](https://github.com/StollLab/EasySpin/commit/eb435443f993f7900d07459a642fdb984dd1ee01).
