### ISSUE TITLE
Simulating oriented films

### ISSUE THREAD

**Issue by stestoll** [StollLab/EasySpin#107]
As of 5.2.13, it is not possible to directly simulate the orientation dependence of EPR spectra from a sample with paramagnetic centers partially aligned in oriented films. Currently, using ```Exp.Ordering``` and ```Exp.CrystalOrientation``` (the only way to specify sample orientation, if it it not a crystal) are mutually exclusive: ```pepper``` throws an error.

Even if this error is removed, there is a problem: ```Exp.Ordering``` gives populations of molecular-frame orientations relative to the lab frame, so that rotating ```Exp.CrystalOrientation```, which rotates the crystal frame relative to the lab frame, has no effect on the spectrum.

Here is short example:

```matlab
clear
Sys.g = [2 2.1 2.2];
Sys.lw = 1;

Exp.mwFreq = 9.5;
Exp.Harmonic = 0;

[B,spc0] = pepper(Sys,Exp);

Exp.Ordering = 5;
Exp.CrystalOrientation = [0 0 0];
[B,spc1] = pepper(Sys,Exp);
Exp.CrystalOrientation = [0 pi/4 0];
[B,spc2] = pepper(Sys,Exp);

plot(B,spc0,B,spc1,B,spc2);
legend('powder','thete = 0','theta = pi/4');
```

To solve this issue cleanly, an additional frame is needed that is attached to the sample that is being rotated. Overall: (1) lab frame, (2) sample frame, (3) crystal/film frame, (4) molecular frame, (5) tensor frames. Rotations would change (1)-(2), sample orientation in the EPR tube would be specified using (2)-(3), and partial ordering of spin systems in films etc would be given with (3)-(4).

This is likely a major change. The math is simple. The challenges are (a) identifying all possible sample situations, which should also include dynamic regimes such as SRLS; (b) finding the right names for the frames to cover all possible sample situations; (c) backwards compatibility for crystal simulations.

**Comment by spribitzer** [comment]
related to this is the issue of rotating the molecular frame (g frame, etc.) in the `saffron` subfunction `rotatesystem`.
`rotatesystem` currently is a hack that rotates the g frame, etc. This is logically flawed. The rotation for the powder averaging should not affect the tensor frames.
