### ISSUE TITLE
spidyan (saffron, thyme): add support for simultaneous mw and rf pulses

### ISSUE THREAD

**Issue by stestoll** [StollLab/EasySpin#124]
the interface of the pulse propagation engine does not allow to simultaneously irradiate with pulses at two different frequencies .

currently this can be done in a hacky way: the undocumented feature of directly feeding IQs to spidyan (instead of a pulse definition) in combination with the option for using Exp.mwPolarization and custom excitation operators should allow to assign one (custom) excitation operator to the real part of the provided IQ (e.g. mw pulse) and the other excitation operator for the complex part to the imag of IQ (rf pulse).

Conceptually:

```
#!matlab

BothPulses.IQ = real(mwPulse) + imag(rfPulse);
Opt.ExcOperator = {sop([1/2 1/2],'xe')}+i{sop([1/2 1/2],'ex')};

Exp.mwPolarization = 'circular'; 

Exp.Sequence = {BothPulses};

spidyan(Sys,Exp)


```

it might be worth adding an interface for this. implementation wise it is rather simple on the level of calculating the propagators, the bookkeeping is trickier

(it also might require a rethinking of the undocumented, current implementation of providing user defined IQs)

**Comment by spribitzer** [comment]
I added an example to the documentation (134e662).
If we decide this is something we want to implement in a more robust way (if there is a demand), we can reopen this issue.
