### ISSUE TITLE
Matlab version support in EasySpin 6

### ISSUE THREAD

**Issue by stestoll** [StollLab/EasySpin#160]
The oldest Matlab version that EasySpin 5.2.x supports is the ancient **R2007b**.

For EasySpin 6, we will change this lower limit to a more recent version. Some relevant changes over the course of recent Matlab versions:

* **R2014b** introduced an overhaul of the handle graphics system - numeric handles are replaced by object handles.
* **R2016b** introduced implicit singleton expansion - this is very useful when dealing with large datasets such as MD data in `mdhmm`, `cardamom`, etc. It also introduced the string data type (`"asd"`) that can replace the character array type (`'asdf'`); and local functions in scripts. 
* **R2017a** introduces `"..."` syntax for strings
* **R2018a** introduced a new storage format for complex numbers - interleaved instead of re/im separate.
* **R2018b** completed support for arrays of strings.
* **R2018b** interactive plots, axes toolbar
* **R2019b** introduced dot indexing into functions (`gca().FontSize`), and introduced function argument validation (`arguments ... end`); also `tiledlayout` and `nexttile`

Minimally, I think **R2016b** should be required, due to the utility of the singleton expansion. Maybe a more recent version.

**Comment by stestoll** [comment]
Commit a285a926ddd34217c06ef2265adf3fec8b6f6e12 bumped minimal required version to R2016b.

**Comment by stestoll** [comment]
Another aspect to consider is that the App Designer GUI framework has improved substantially since R2016b. It's unclear whether EasySpin should switch to App Designer or stick with the old GUI framework.

**Comment by stestoll** [comment]
Commit https://github.com/StollLab/EasySpin/commit/94936cb21a8f20cdd79e00959420846f983ba7ba bumped minimum required version to R2017a to support `"..."` syntax for strings.

**Comment by stestoll** [comment]
To use `matlab.net.base64decode` (for reading Magnettech spectrometer XML files), R2016b is required.

**Comment by stestoll** [comment]
Decision: The oldest officially supported MATLAB version for EasySpin 6 will be R2017a.

**Comment by stestoll** [comment]
Reopening this, since releases newer than R2017a offer benefits. A small selection:

- R2022b (9.13): dictionaries
- R2022a (9.12): new Pcode format; still can generate older Pcode with `"-R2007b"` option
- R2020a (9.8): UTF-8 encoding of script and function files
- R2019b (9.7): `tiledlayout`, `nexttile`
- R2018b (9.5): complete support for string arrays, `xline` and `yline`
- R2018a (9.4): new complex-number storage format: re/im interleaved storage instead of separate storage; mex supports this
- R2017b (9.3): `vecnorm`: vector-wise norm of arrays

UTF-8 support and `tiledlayout`/`nexttile` are particularly useful.

In addition, `uifigure`-based apps have been getting more complete features, and their performance has been improving.

Then there are the continuously improving Live Scripts, which EasySpin could at some point start using for tutorials or examples.

Upgrade cost to the user base might be smaller than originally thought, because most EasySpin users are in academia, and many universities have MATLAB subscriptions and provide licenses for modest fees that allow upgrades.

**Comment by cetait** [comment]
The newest version of the `esfit` GUI, including global fitting display, requires at least Matlab R2021b. On older Matlab versions, `esfit` switches to the legacy version if the GUI is requested. Script-based use of `esfit` is not affected (global fitting works).

`isotopes` does not work for Matlab 2017a (error setting table data), but works from R2018b onwards.

**Comment by cetait** [comment]
This is an overview of the Matlab version that people who signed up to the EasySpin spin polarisation online workshop last year (200 registrations) had indicated:
![MatlabVersion](https://github.com/StollLab/EasySpin/assets/55527598/f4b127ff-3d30-4728-9101-08fb3ee4b702)

About 54% have R2021b or a newer version, 77% have R2019b or newer. Of the people who indicated an older Matlab version than R2021b, about 50% are from institutions where other people have indicated newer Matlab versions.

**Comment by stestoll** [comment]
Conclusion after discussion on Zoom:

- R2021b is the minimum required version for ES6.
- but EasySpin should only issue warning, not error, if run on older versions.
