### ISSUE TITLE
test on commit

### ISSUE THREAD

**Issue by spribitzer** [StollLab/EasySpin#163]
Instead of running tests manually, this should be automatized.

To take into consideration:
- Should tests run on every commit, or only commits to `master`
- Run tests against the source code or a packaged version of EasySpin
- Should tests run on all three platforms?
- Against what MATLAB version do we need to test (this links to issue #160 )
-  Currently testing takes >5 minutes. If we test on every single commit, depending on the number of commits a month, this could eat up our contingent of available GitHub action time.

**Comment by stestoll** [comment]
The number of contributors is sufficiently small (and they mostly don't break tests) that this is currently not an issue.
