### ISSUE TITLE
esftit_swarm - TolFun absolute, not relative as in documentation

### ISSUE THREAD

**Issue by michkern** [StollLab/EasySpin#189]
Hi,

I've been testing the various fitting algorithms and noticed that with particle swarm, the fit was not finishing even after I stopped seeing any changes in the error (which was around 1e-2). I, therefore, checked the documentation to find the constraining parameter and its definition, which I've found:

> TolFun
>Termination tolerance for error function value change. 

Which to me implies that it compares the difference between the last two iterations, and when this value is smaller than TolFun, the fit terminates. I've tried many different values  until I found that my fit stops only when I make the TolFun parameter larger than the absolute value of the error. Upon inspection of the code in `esfit_swarm.m`, as far as I get it, this is indeed the case:

line 81:`if (globalbesterror<FitOpt.TolFun), stopCode = 3; break; end`

I would, therefore, suggest to either change the documentation or change the code to compare the difference between `globalbesterror` and the error in the current iteration to TolFun. I would prefer the latter.
It would also be useful to mention the default value of 1e-5 in the documentation.

Edit: Language.

**Comment by stestoll** [comment]
I agree that the current termination criterion is not optimal.

However, using iteration-to-iteration min-error change doesn't work for this algorithm, as it happens quite often that the min-error stays unchanged from one iteration to the next.

We'll have to look for better convergence criteria.

**Comment by michkern** [comment]
> However, using iteration-to-iteration min-error change doesn't work for this algorithm, as it happens quite often that the min-error stays unchanged from one iteration to the next.

True. Maybe it would be useful to add an option for the termination criterion to be the number of iterations, similar to the genetic algorithm, and/or the number of iterations without a change in min-error.
