### ISSUE TITLE
Suggestion: add RMSD output of esfit into documentation

### ISSUE THREAD

**Issue by michkern** [StollLab/EasySpin#190]
I've just discovered that there is an undocumented option when using `esfit` without GUI to output the RMSD as well, `[BestSys,BestSpc,rmsd]=esfit(...)`. At least I didn't find it either in `esfit` or `userguide_fitting` docs.  I would suggest to add this into documentation, since it is quite useful when doing for example batch fitting procedures or comparing different esfit inputs, and spares the user the time of calculating it again, even if it is a few lines of code.

P.S. I wasn't sure if this was the correct place to post this. Should stuff like this be discussed in the forum first?

**Comment by stestoll** [comment]
Yes, this should be documented. Note however that the third output is the vector of residuals, not the rmsd.
