### ISSUE TITLE
cardamom: better names for Par.dt and Par.Dt

### ISSUE THREAD

**Issue by stestoll** [StollLab/EasySpin#201]
These two field names don't convey what they represent, are easily mixed up, and are just one typo away from each other.

Proposal:  `Par.dtRot` and `Par.dtSpin`

**Comment by pdmartin14** [comment]
Agreed, I will make the appropriate changes in the pull request.

**Comment by pdmartin14** [comment]
Actually, it looks like `dtStoch` and `dtQuant` are used internally, whereas the log messages use "Spatial propagation" and "Quantum propagation".

I vote for either 
- `Par.dtSpatial` and `Par.dtSpin`
- or `Par.dtStoch` and `Par.dtQuant`

Thoughts?

**Comment by stestoll** [comment]
`Par.dtSpatial` and `Par.dtSpin` are good. They are clear, referring to the spatial and the spin degrees of freedom. `dtStoch` is less general, as it implies that spatial propagation is stochastic - which it doesn't necessarily have to be.

**Comment by stestoll** [comment]
Resolved with commit a9c7475
