### ISSUE TITLE
Convolutional broadening ignores the kind of sweep (field or frequency) in dispersion

### ISSUE THREAD

**Issue by sikuenstner** [StollLab/EasySpin#202]
According to the steady state solution of the _Bloch_ equations (omitting saturation), the line shape of the absorption is a _Lorentzian_ as
`\chi'' \propto 1/(1+\Omega^2)`,
while the dispersion has the following line shape:
`\chi' \propto \Omega/(1+\Omega^2)`,

the resonance offset \Omega is defined as
`\Omega = \omega_{mw} - \omega_L`
with with \omega_{mw} being the microwave frequency, and \omega_L the _Larmor_ frequency which is in turn defined as
`\omega_L = -\gamma B_0`.
Sometimes the resonant offset is defined as difference of _Larmor_ frequency and microwave frequency.

The difference of a field sweep in contrast to a frequency sweep is the variable that is changed in the resonance offset (either \omega_{mw} or the _Larmor_ frequency). This means that performing a field sweep in up-field direction (B_{start} < B_{stop}) is the same as performing a frequency sweep in down-frequency direction (f_{start} > f_{stop}). Hence, to compare field and frequency sweeps, one of them has be displayed reversely.

For a single _Lorentzian_ line as predicted by _Bloch_'s equations (seen above), this is only seen in the dispersion, since it has the resonance offset in numerator.

This inversion, however, is ignored when using convolutional broadening in Easyspin by specifying Sys.lw or Sys.lwpp while performing a simulation of a dispersion line. That would correspond to a redefinition of the resonant offset.

I am not quite sure if this behaviour is intended but at least it should be indicated in the documentation. Attached is a script with which you can reproduce the explanation.

[Easyspin_dispersion.zip](https://github.com/StollLab/EasySpin/files/5482966/Easyspin_dispersion.zip)

**Comment by stestoll** [comment]
This is indeed a bug in EasySpin. I agree that the dispersion lineshape of a field sweep and a frequency sweep should be inverted relative to each other. It's likely an easy fix.
