### ISSUE TITLE
rescale.m

### ISSUE THREAD

**Issue by ecizmar** [StollLab/EasySpin#209]
rescale.m called by esfit.m does have the same name as Matlab function "rescale" introduced in Matlab R2017b, in result, esfit fails when FitOpt.Scaling is defined

**Comment by stestoll** [comment]
This is an unfortunate consequence of MATLAB's design where all functions share the same namespace.

One workaround is to make sure that the EasySpin folder `easyspin-x.y.z/easyspin` is on the MATLAB path **before** the path to the other function (`toolbox/matlab/datafun` I believe). In this case, MATLAB's `rescale` will be shadowed, and `esfit` will call EasySpin's `rescale`.

For EasySpin version 6, we can consider renaming the function to avoid this clash.

**Comment by stestoll** [comment]
When pressing F1 on `rescale` in the editor, the documentation page for MATLAB's `rescale` function appears, even though it is shadowed:

```
>> which -all rescale
C:\easyspin\easyspin\rescale.m
C:\Program Files\MATLAB\R2021a\toolbox\matlab\bigdata\@tall\rescale.m  % tall method
C:\Program Files\MATLAB\R2021a\toolbox\matlab\datafun\rescale.m        % Shadowed
```
Tested on R2021a.

It looks like we might need to rename the EasySpin function.

**Comment by ecizmar** [comment]
Thank you, it is probably easier to rename the function that most of the users of EasySpin do not use directly instead of searching for workarounds.

**Comment by stestoll** [comment]
I filed a service request with MathWorks regarding this. Response is that they won't fix this behavior. So EasySpin has to rename the function.
