### ISSUE TITLE
Blochsteady - Calculation of the number of points of time traces and Fourier order

### ISSUE THREAD

**Issue by sikuenstner** [StollLab/EasySpin#210]
In the current version of blochsteady, the standard number of points for the time traces is 1000 points (line 61 ff.) as set upon input checking:
```
if ~isfield(Options,'nPoints')
  Options.nPoints = 1000;
end
```

In the description of the function, however, it says that it is automatically determined (from the Fourier order). In line 194
`nPoints = Options.nPoints; `
the number of points from Options.nPoints is used, effectively disabling the following automatic determination of the number of points (lines 195-197): 
```
if isempty(nPoints)
  nPoints = 2*kmax-1;
end
```
unless `Option.nPoints = [];` is specified for the input of blochsteady.

To enable the automatic determination of the no. of points, an immediate solution would be to replace line 62 by
 `Option.nPoints = [];`

If `nPoints < 2*kmax-1` the output of blochsteady will be wrong unless  `Options.nPoints` is a value that is high enough as can easily be seen by
`blochsteady(2,1,1,0,0.1,100,50) `

Since Options is not a mandatory field to specify, I think it should be changed to ensure a safe operation of the function.

Additionally, I am not quite sure about the calculation of the Fourier order. In the code, two estimations for the maximum Fourier order are performed:
1) Regarding the modulation amplitude and frequency as explained in Tseitlin et al. (2013) (https://doi.org/10.1007/s00723-013-0494-2). Lines 111ff.
2) Regarding T2. Lines 120ff.

The **lower** of the two numbers is taken as the maximum _Fourier_ order. When I perform a simulation, with the following code, dents appear on the trailing edge of the rapid scan time trace, which are nonphysical in my opinion.

```
Options.nPoints = [];                   % enable calculation of no. of points from Fourier order
blochsteady(2,1,1,0,0.1,100,50,Options) 
```

If the larger of the two estimations are used (replace min with max in line 127), the dents disappear as I would expect from a rapid scan signal.

**Comment by stestoll** [comment]
fixed in 183f6bbacc5732b296b2ed9034711dc60385675e
