### ISSUE TITLE
substitute rescale to rescaledata?

### ISSUE THREAD

**Issue by yah0r** [StollLab/EasySpin#212]
Error using rescale
Too many output arguments.
Error in esfit>runFitting (line 478)
[fit,scale] = rescale(fitraw,fitdat.data,fitdat.FitOpts.Scaling);
Error in esfit (line 373)
result = runFitting();

**Comment by stestoll** [comment]
This is now implemented for v6.0 with 3a79b9a864e8a18dd55b9ce4efaa45b3351b0195, see also #209.
