### ISSUE TITLE
Add function signatures (for code suggestions and completions)

### ISSUE THREAD

**Issue by stestoll** [StollLab/EasySpin#236]
MATLAB now supports code suggestions and completion also for third-party toolboxes. We should make use of this, since it will help user remember which arguments to use for a particular EasySpin function and in which order.

Documentation see here: https://www.mathworks.com/help/matlab/matlab_prog/customize-code-suggestions-and-completions.html

This will require a `functionSignatures.json` file in the main toolbox folder.

The file will contain entries like this:

```
"datasmooth": {
    "inputs":
    [
        {"name":"y", "kind":"required", "type":["numeric"], "purpose":"data"},
        {"name":"m", "kind":"required", "type":["scalar"], "purpose":"filter width (2*m+1)"},
        {"name":"mode", "kind":"ordered", "type":["choices={'binom','flat','savgol'}"], "purpose":"filter type"},
        {"name":"p", "kind":"ordered", "type":["scalar"], "purpose":"filter order (Savitzky-Golay only), default 0"},
        {"name":"dif", "kind":"ordered", "type":["scalar"], "purpose":"derivative order (Savitzky-Golay only), default 0 (no derivative)"}
    ]
},
```

**Comment by redman-a** [comment]
Currently in EasySpin there are many functions where the html/online documentation and the `help` docstring use slightly different names for input arguments (largely differences in capitalisation and/or contractions). Which is the preferred source for the JSON `"name"` argument?

**Comment by stestoll** [comment]
In general, the html documentation should take precedence. The `help` doc hasn't been maintained as well.
