### ISSUE TITLE
Implement photoselection

### ISSUE THREAD

**Issue by cetait** [StollLab/EasySpin#239]
Implement (magneto)photoselection into `pepper`. The user needs to supply a few pieces of information:

- `Sys.tdm`: transition dipole moment orientation in molecular frame (two Euler angles)
- `Exp.LaserPolarization`: a percentage to indicate how strongly the laser is polarized (0 = depolarized)
- `Exp.LaserPolarizationAngle`: angle between B0 and E-field of laser

(field names here are just quick proposals, better names might exist)

**Comment by stestoll** [comment]
Better interface:
- `Exp.lightMode = ''`  or `'iso'`:  no photoexcitation, or isotropic photoexcitation
- `Exp.lightMode = 'perp'`: beam perpendicular to B0, E-field perpendicular to B0
- `Exp.lightMode = 'para'`: beam perpendicular to B0, E-field parallel to B0
- `Exp.lightMode = 'unpol': beam perpendicular to B0, unpolarized
- `Exp.lightMode = {k alpha}`: explicitly give beam direction `k` and polarization angle `alpha`; use `alpha=NaN` for unpolarized beam

To include an admixture of an isotropically excited spectrum, provide that fraction in a separate field that could be called `Exp.lightScatter` or `Exp.lightIsotropic` or similar.

**Comment by cetait** [comment]
I would propose `lightBeam` as a more appropriate field name than `lightMode` in this context. The downside would be that there is no longer a parallel to the microwave excitation mode specification.

**Comment by stestoll** [comment]
I agree that `lightBeam` is better. The downside is not too terrible.

**Comment by stestoll** [comment]
There is another issue that needs to be addressed: powder averaging over the third Euler angle `chi` of the sample orientation. This angle does not affect the resonance field, and without photoexcitation the integral over this angle to get the total intensity is simple. However, the dependence of the photoselection weight on this angle depends strongly on the TDM orientation, the propagation direction, and the polarization angle.

Here is a script that illustrates this dependence:
```matlab
clear, clc

%rng(8723498);

tdm = [rand*2*pi rand*pi]; % TDM orientation in mol frame

k = [rand*2*pi rand*pi]; % light propagation direction in lab frame
alpha = rand*2*pi; % polarization angle
%alpha = NaN; % unpolarized light

% Orientation of lab frame relative to mol frame
phi = rand*2*pi;
theta = rand*pi;
chi = linspace(0,2*pi,361); % third angle, does not affect resonance field

% Calculate photoselection weights for all spin center orientations that
% give the same resonance field.
for ichi = 1:numel(chi)
  ori = [phi theta chi(ichi)];
  w(ichi) = photoselect(tdm,ori,k,alpha);
end

% Plotting
plot(chi*180/pi,w);
xticks(0:30:360);
axis tight
grid on
xlabel('\chi (deg)')
ylabel('photoselection weight')
ylim([0 1]);
```

**Comment by stestoll** [comment]
This is implemented now in the PR.
