### ISSUE TITLE
Some sample script errors in dev 49

### ISSUE THREAD

**Issue by cerium1925** [StollLab/EasySpin#269]
for details, see attached.
[Uploading Some sample script errors.docx…]()

**Comment by stestoll** [comment]
Please post these errors directly in here.

**Comment by cerium1925** [comment]
<img width="514" alt="Screenshot 2022-11-13 143216" src="https://user-images.githubusercontent.com/110143023/201509121-b8f4c83d-1748-4a59-969d-424b0cdb9ac2.png">
<img width="262" alt="Screenshot 2022-11-13 143251" src="https://user-images.githubusercontent.com/110143023/201509125-194a67e8-3dc8-4b76-a7f4-bc17fbcbe4fb.png">
<img width="530" alt="Screenshot 2022-11-13 143435" src="https://user-images.githubusercontent.com/110143023/201509128-a3787cec-6a71-4c6d-bddb-263b17df7d2d.png">

**Comment by stestoll** [comment]
Thanks for reporting! All three bugs are fixed now!
