### ISSUE TITLE
Misspelling errors

### ISSUE THREAD

**Issue by cerium1925** [StollLab/EasySpin#270]
<img width="1014" alt="Screenshot 2022-11-15 111453" src="https://user-images.githubusercontent.com/110143023/201818047-0cafd57a-2606-4d44-8a76-8240ebb59809.png">

**Comment by stestoll** [comment]
This is not a misspelling. This is a MATLAB warning in `eigs`. It is present in R2016b, but was removed in a refactor in a later release, so it's absent in R2022b.
