### ISSUE TITLE
levelsplot function feature enhancements suggestions

### ISSUE THREAD

**Issue by cerium1925** [StollLab/EasySpin#271]
Although we can beautify the energy level diagram with the custom output of the levels function. But I personally think it would be better if we could integrate levelsplot's output parameters such as field, direction, and frequency labeling directly into this function.
<img width="439" alt="Screenshot 2022-11-17 112302" src="https://user-images.githubusercontent.com/110143023/202348148-2d239025-6243-4439-9fc8-11b66c06f951.png">
<img width="263" alt="Screenshot 2022-11-17 112330" src="https://user-images.githubusercontent.com/110143023/202348157-a52ec860-c92c-42fa-88d5-d20b9c7e2d76.png">

**Comment by cerium1925** [comment]
Orientation, especially.

**Comment by stestoll** [comment]
I don't quite understand what you are suggesting. Please clarify.

**Comment by cerium1925** [comment]
<img width="479" alt="1" src="https://user-images.githubusercontent.com/110143023/208294584-6989437d-4488-4dab-8987-2c73f9f0027d.png">
<img width="486" alt="2" src="https://user-images.githubusercontent.com/110143023/208294585-1e335379-cc94-4fa1-a344-a956098b6c87.png">
1. As above Figs show, we can add infos of ori or mw in form of MATLAB legend or title functions. because the ori or mv is most   important contents.
2. The default mv annotation is not the same size as the self-added MATLAB title/legend font?
3. The content of the matlab function title will change as the mouse moves? Random "level nmu" or "transition amplitude and energy level"?

**Comment by cerium1925** [comment]
<img width="274" alt="Screenshot 2022-12-18 200323" src="https://user-images.githubusercontent.com/110143023/208297336-eb105cf9-cb25-4d63-bb6d-e898a14d07e9.png">
[xyz.txt](https://github.com/StollLab/EasySpin/files/10253770/xyz.txt)

Demo script

**Comment by stestoll** [comment]
Good suggestion to display the orientation!
