### ISSUE TITLE
hccm function bug

### ISSUE THREAD

**Issue by cerium1925** [StollLab/EasySpin#274]
<img width="152" alt="Screenshot 2022-12-18 210226" src="https://user-images.githubusercontent.com/110143023/208299951-3baae25b-7962-48a8-9c26-eac5f5414f47.png">
<img width="518" alt="Screenshot 2022-12-18 210242" src="https://user-images.githubusercontent.com/110143023/208299952-d4a19f82-57d2-49f8-a5a5-01fcddb5fedb.png">

Dot product?

**Comment by stestoll** [comment]
This error says that your computer does not have enough memory to accommodate the requested calculation. 

`J` has size `[n p]`, where `n` is the number of data points, and `p` is the number of fitting parameters.  `pinvJTJ` has size `[p p]`. 

It's not clear how you can get a 65536x65536 matrix size. What is `n` and `p` in your case?

**Comment by cerium1925** [comment]
I provide one simulation data and one real test data. using esft function to Extract EPR parameters.
[Reference Data.zip](https://github.com/StollLab/EasySpin/files/10255471/Reference.Data.zip)


SIm_data: Al_#1;

real test_data: 2CSP-001-130K;

**Comment by stestoll** [comment]
Please provide a complete concise script that generates the error.

**Comment by cerium1925** [comment]
[Al_#1.txt](https://github.com/StollLab/EasySpin/files/10256282/Al_.1.txt)

**Comment by stestoll** [comment]
Thanks, I can reproduce this now. Looks like some memory waste in `hccm`, easy to improve.
