### ISSUE TITLE
Provide a portable pdf or chm version of docsrc?

### ISSUE THREAD

**Issue by cerium1925** [StollLab/EasySpin#275]
html format is convenient in PC platform. however，it is reading-restricted in offline mobile devices, such as pad, android or ios mobile phones. These docs  are scattered, which makes communication particularly inconvenient.  so I think the format of .pdf or .chm (Compiled HTML Help file) is one considering suggestion.

**Comment by stestoll** [comment]
There is currently no simple pathway of creating a PDF or CHM file of the documentation. A PR is welcome!
