### ISSUE TITLE
Improve 'Isotope' window readability

### ISSUE THREAD

**Issue by Liam-Twomey** [StollLab/EasySpin#292]
I suggest adding column headings to the data table in the `isotopes.m` GUI, to improve ease of use. I have implemented this in my fork (see below) and am ready to PR, but I wanted to be respectful of the contribution rule against PRs which do not respond to an existing issue.
<img width="403" alt="easyspin-isotopes-mod" src="https://github.com/StollLab/EasySpin/assets/61964255/2435eabd-6e97-4319-a931-4ad13467d6bf">
I think this falls under "interface or implementation improvements of an existing function", but I understand if you think it falls under "tiny code refactors and 'beauty' edits".

**Comment by stestoll** [comment]
This definitely improves usability, so it's a welcome addition - thank you!

Please submit PR, making sure it's up-to-date relative to the main branch.
