### ISSUE TITLE
add a column for the gyromagnetic ratio in isotopoes function ?

### ISSUE THREAD

**Issue by cerium1925** [StollLab/EasySpin#303]
It is recommended to separately add a column for the gyromagnetic ratio in isotopoes function.
https://www.kherb.io/docs/nmr_table
<img width="796" alt="Screenshot 2023-08-25 213849" src="https://github.com/StollLab/EasySpin/assets/110143023/9db73cb6-c4db-4141-ab3b-fd329c3f9496">
.html

**Comment by stestoll** [comment]
Good suggestion!
