### ISSUE TITLE
Support mt2mhz and mhz2mt in 6.0

### ISSUE THREAD

**Issue by stestoll** [StollLab/EasySpin#306]
These are widely used functions (based on posts from user forum), so it might be useful to keep these functions supported instead of issuing an error. Maybe a warning can be issued, and they should no longer be included in the documentation.,

**Comment by sikuenstner** [comment]
I agree.

**Comment by stestoll** [comment]
Decision is to keep them fully supported. Implemented in https://github.com/StollLab/EasySpin/pull/308.
