### ISSUE TITLE
Is the output of ES core pepper and other functions stored in rows?

### ISSUE THREAD

**Issue by cerium1925** [StollLab/EasySpin#319]
<img width="320" alt="image" src="https://github.com/StollLab/EasySpin/assets/110143023/1095a21d-dc51-47c0-ac29-f7e037b8775d">

According to the original data storage logic of maltab, ES will obviously store in columns much faster, especially when functions such as pepper are called repeatedly.

**Comment by stestoll** [comment]
The time needed to allocate and assign the output spectral data array in `pepper` is negligible compared to the actual calculation.

`pepper` always returns the field dimension along the row of the spectral data array. If separate transitions were requested, `pepper`returns a 2D array with one transition spectrum per row.
