### ISSUE TITLE
Pulse shaping: implement HSn frequency modulation function

### ISSUE THREAD

**Issue by stestoll** [StollLab/EasySpin#320]
For higher-order HSn pulses (n>1), `pulse` implements the amplitude modulation function (order is provided via `Par.n`), but it does not provide the associated frequency modulation function. This should be implemented.

For the math, see for example Table 1 in https://doi.org/10.1006/jmra.1996.0110

**Comment by cetait** [comment]
Higher order HSn pulses (with offset-independent adiabaticity) are currently implemented through `Par.Type = 'sech/uniformQ`, which returns both amplitude and frequency modulation functions (if n=1 this is equivalent to `'sech/tanh'`). Is this what you mean?
In the documentation, in the description of `uniformQ`, it says that this can be used for nth order sech pulses. Would it be useful to add the HSn notation or to also mention it as a comment in the description of the amplitude modulation functions under `'sech'`?

**Comment by stestoll** [comment]
I see. I think this really just a documentation issue then - mentioning it under the `sech` amplitude would be good.
