### ISSUE TITLE
Physical constants 2022 CODATA

### ISSUE THREAD

**Issue by redman-a** [StollLab/EasySpin#340]
I have noticed that the new 2022 CODATA values were accepted in May released on 20 May 2024 (e.g. https://pml.nist.gov/cuu/Constants/). I'm assuming that EasySpin will be updating to these? I'm happy to work on this and can start working on a pull request straight away. Please let me know if someone else has already taken this on or if you don't want the values updating.

**Comment by stestoll** [comment]
A PR that updates the constants would be great. Thanks!

**Comment by stestoll** [comment]
Thanks for this contribution.
