### ISSUE TITLE
Logic bug in orifun_M2L func？

### ISSUE THREAD

**Issue by cerium1925** [StollLab/EasySpin#344]
bugs：

1. This condition will never be met？

    for iOri = numel(phi):-1:1
      Fchi = @(chi) oriweight(f,R_S2L,phi(iOri),theta(iOri),chi);
      w(iOri) = integral(Fchi,0,2*pi);
    end

2.  This defined function is not called?

function ow = oriweight(f,R_S2L,ph,th,chi)
for iChi = numel(chi):-1:1
  R_M2L = erot(ph,th,chi(iChi));
  R_L2M = R_M2L.';
  R_S2M = R_L2M*R_S2L;
  [alpha_S2M,beta_S2M,gamma_S2M] = eulang(R_S2M,true);
  ow(iChi) = f(alpha_S2M,beta_S2M,gamma_S2M);
end

3. solutions：The following revised code does not change the original calculation logic and results

revised code:

function w = orifun_M2L_es(f, R_L2S, phi, theta, chi)
    % orifun_M2L  Evaluates ordering function
    %
    %  w = orifun_M2L(f,R_L2S,phi,theta)
    %  w = orifun_M2L(f,R_L2S,phi,theta,chi)
    %
    % Inputs:
    %   phi    phi angle for the transformation from mol to lab frame
    %   theta  theta angle for the transformation from mol to lab frame
    %   chi    chi angle for the transformation from mol to lab frame
    %          if omitted, f is integrated over chi
    %   R_L2S  transformation matrix from lab to sample frame
    %   f      orientational distribution function, taking as input
    %          Euler angles from sample frame to molecular frame
    %
    % Output:
    %   w      weights, one for each element in phi/theta,
    %          integrated over chi if chi is not given

    R_S2L = R_L2S.';

    integrateChi = nargin == 4;

    if integrateChi
        w = zeros(size(phi)); % Initialize w
        for iOri = numel(phi):-1:1
            Fchi = @(chi) oriweight(f, R_S2L, phi(iOri), theta(iOri), chi);
            w(iOri) = integral(Fchi, 0, 2*pi);
        end
    else
        w = zeros(size(phi)); % Initialize w
        for iOri = numel(phi):-1:1
            R_M2L = erot(phi(iOri), theta(iOri), chi(iOri));
            R_L2M = R_M2L.';
            R_S2M = R_L2M * R_S2L;
            [alpha_S2M, beta_S2M, gamma_S2M] = eulang(R_S2M, true);
            w(iOri) = f(alpha_S2M, beta_S2M, gamma_S2M);
        end
    end
end

function ow = oriweight(f, R_S2L, ph, th, chi)
    ow = zeros(size(chi)); % Initialize ow
    for iChi = numel(chi):-1:1
        R_M2L = erot(ph, th, chi(iChi));
        R_L2M = R_M2L.';
        R_S2M = R_L2M * R_S2L;
        [alpha_S2M, beta_S2M, gamma_S2M] = eulang(R_S2M, true);
        ow(iChi) = f(alpha_S2M, beta_S2M, gamma_S2M);
    end
end

**Comment by stestoll** [comment]
These parts of the code are needed for `bruteforce==True`. Although this is not used in the released code, it is useful for development and testing purposes.
