### ISSUE TITLE
Are there potential input errors in manually entered mathematical expressions?

### ISSUE THREAD

**Issue by cerium1925** [StollLab/EasySpin#345]
In this context, I believe that text exported using software like Mathematica may be more accurate, as the physical and mathematical formulas in many early documents were prone to printing errors.

Based on this, I tested a nb script, which can import the results of nb calculations and be called directly by matlab.

1. nb code
2. matlab load txt
3.  matlab using expressions
such as:

persistent expressions;
if isempty(expressions)
    expressions = load_wigner_expressions('WignerD_Expressions.txt');
end

codes:

1. nb code: 

(*Define the range of J values you are interested in*)
Jvalues = {1/2, 1, 3/2, 2, 5/2, 3, 7/2, 4, 9/2, 5, 11/2, 6};

WignerDExpressions[J_] := 
 Module[{alpha, beta, gamma, m1, m2, expressions, expr}, 
  expressions = {};
  Do[expr = WignerD[{J, m1, m2}, alpha, beta, gamma];
   expressions = 
    Append[expressions, {J, m1, m2, 
      ToString[
       FullSimplify[
        expr /. {alpha -> \[Alpha], beta -> \[Beta], 
          gamma -> \[Gamma]}, {Element[\[Alpha], Reals], 
         Element[\[Beta], Reals], Element[\[Gamma], Reals]}], 
       FormatType -> StandardForm]}], {m1, -J, J, 1}, {m2, -J, J, 
    1}];
  expressions]

(*Generate expressions for all J values*)
allExpressions = 
  Flatten[Table[WignerDExpressions[J], {J, Jvalues}], 1];

(*Export the expressions to a file*)
Export["WignerD_Expressions.txt", allExpressions, "Table"]

(*Display the generated expressions*)
allExpressions

2. matlab call funs;

function expressions = load_wigner_expressions(filename)
% Load Wigner D-matrix expressions from a text file
%
% expressions = load_wigner_expressions(filename)
%
% Inputs:
%   filename - Path to the text file containing expressions
%
% Outputs:
%   expressions - Struct array with fields J, m1, m2, expression

fid = fopen(filename, 'r');
if fid == -1
    error('Could not open file: %s', filename);
end

% First pass: count lines
num_lines = 0;
while ~feof(fid)
    line = fgetl(fid);
    if ischar(line)
        num_lines = num_lines + 1;
    end
end
fclose(fid);

% Preallocate struct array
expressions = struct('J', cell(1, num_lines), 'm1', cell(1, num_lines), 'm2', cell(1, num_lines), 'expression', cell(1, num_lines));

% Second pass: read lines and populate struct array
fid = fopen(filename, 'r');
index = 1;
while ~feof(fid)
    line = fgetl(fid);
    if ~ischar(line)
        break;
    end
    % Parse the line assuming the format: J, m1, m2, expression
    tokens = strsplit(line, ',');
    if numel(tokens) == 4
        expressions(index).J = str2double(tokens{1});
        expressions(index).m1 = str2double(tokens{2});
        expressions(index).m2 = str2double(tokens{3});
        expressions(index).expression = strtrim(tokens{4});
        index = index + 1;
    end
end

fclose(fid);
end

**Comment by cerium1925** [comment]
[test code.txt](https://github.com/user-attachments/files/16333866/test.code.txt)


> In this context, I believe that text exported using software like Mathematica may be more accurate, as the physical and mathematical formulas in many early documents were prone to printing errors.
> 
> Based on this, I tested a nb script, which can import the results of nb calculations and be called directly by matlab.
> 
> 1. nb code
> 
> <img alt="1" width="1154" src="https://private-user-images.githubusercontent.com/110143023/350976805-93d419d9-f5ad-488c-ae19-a9c7f8ae1242.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NTQ2MDEsIm5iZiI6MTcyMTY1NDMwMSwicGF0aCI6Ii8xMTAxNDMwMjMvMzUwOTc2ODA1LTkzZDQxOWQ5LWY1YWQtNDg4Yy1hZTE5LWE5YzdmOGFlMTI0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQxMzE4MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDg3NTJlODMyMWViMTFlY2Q2ZTdlYmMxNjRjZmFjOTcyNjRhYjY4NjY4ZDYwOTMwNWY4ZWVlNGJlODVlMjU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.t1GUcAoK6po-ceS_FNwOIOSltae16Js6qGKny6wSSw8"> 2. matlab call nb result. [Uploading load_wigner_expressions.m…]()
> test code：
> 
> nb code: (_Define the range of J values you are interested in_) Jvalues = {1/2, 1, 3/2, 2, 5/2, 3, 7/2, 4, 9/2, 5, 11/2, 6};
> 
> WignerDExpressions[J_] := Module[{alpha, beta, gamma, m1, m2, expressions, expr}, expressions = {}; Do[expr = WignerD[{J, m1, m2}, alpha, beta, gamma]; expressions = Append[expressions, {J, m1, m2, ToString[ FullSimplify[ expr /. {alpha -> [Alpha], beta -> [Beta], gamma -> [Gamma]}, {Element[[Alpha], Reals], Element[[Beta], Reals], Element[[Gamma], Reals]}], FormatType -> StandardForm]}], {m1, -J, J, 1}, {m2, -J, J, 1}]; expressions]
> 
> (_Generate expressions for all J values_) allExpressions = Flatten[Table[WignerDExpressions[J], {J, Jvalues}], 1];
> 
> (_Export the expressions to a file_) Export["WignerD_Expressions.txt", allExpressions, "Table"]
> 
> (_Display the generated expressions_) allExpressions
> 
> 2. matlab call code:
> 
> function expressions = load_wigner_expressions(filename) % Load Wigner D-matrix expressions from a text file % % expressions = load_wigner_expressions(filename) % % Inputs: % filename - Path to the text file containing expressions % % Outputs: % expressions - Struct array with fields J, m1, m2, expression
> 
> fid = fopen(filename, 'r'); if fid == -1 error('Could not open file: %s', filename); end
> 
> % First pass: count lines num_lines = 0; while ~feof(fid) line = fgetl(fid); if ischar(line) num_lines = num_lines + 1; end end fclose(fid);
> 
> % Preallocate struct array expressions = struct('J', cell(1, num_lines), 'm1', cell(1, num_lines), 'm2', cell(1, num_lines), 'expression', cell(1, num_lines));
> 
> % Second pass: read lines and populate struct array fid = fopen(filename, 'r'); index = 1; while ~feof(fid) line = fgetl(fid); if ~ischar(line) break; end % Parse the line assuming the format: J, m1, m2, expression tokens = strsplit(line, ','); if numel(tokens) == 4 expressions(index).J = str2double(tokens{1}); expressions(index).m1 = str2double(tokens{2}); expressions(index).m2 = str2double(tokens{3}); expressions(index).expression = strtrim(tokens{4}); index = index + 1; end end
> 
> fclose(fid); end
> 
> 3. matlab call expression  code
> 
> persistent expressions; if isempty(expressions) expressions = load_wigner_expressions('WignerD_Expressions.txt'); end

![Uploading Screenshot 2024-07-22 210040.png…]()

**Comment by cerium1925** [comment]
<img width="565" alt="Screenshot 2024-07-22 210040" src="https://github.com/user-attachments/assets/45fc1e1c-ad1b-4993-8fda-6daf399e2de3">

**Comment by cerium1925** [comment]
test code; 
[Uploading test code.txt…]()

**Comment by stestoll** [comment]
Thanks for looking into this.

Have a look at the test [wignerd_singlevalues](https://github.com/StollLab/EasySpin/blob/main/tests/wignerd_singlevalues.m).

It numerically tests all explicit expressions hard-coded in [wignerd/littled_explicit](https://github.com/StollLab/EasySpin/blob/02dfbf3ce2885643036de47888ba608310281683/easyspin/wignerd.m#L185) against values calculated using a matrix exponential with `expm`.

The test passes, so the currently implemented explicit expressions are all correct.
